version: '3.1'

services:

  # server:
  #   build: .
  #   ports:
  #   - "9000:8080"
  #   depends_on:
  #   - db
  #   networks:
  #   - default
  

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
    - "5432:5432"
    # networks:
    # - default